githubixx/ansible-role-wireguard

- tasks/main.yml
- tasks/setup-archlinux.yml
- tasks/setup-ubuntu.yml
As per the [ansible loop docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-simple-list) it is preferred to use this new syntax where possible instead of `loop` or `with_items`
> You can pass a list directly to a parameter for some plugins. Most of the packaging modules, like yum – Manages packages with the yum package manager and apt – Manages apt-packages, have this capability. When available, passing the list to a parameter is better than looping over the task.
> update tasks to use the new preferred looping syntax

- CHANGELOG.md
- tasks/setup-centos.yml
This simply adds CentOS/RHEL support. I've tried this out on my own network and it appears to work as expected.
> add CentOS support

- README.md
- templates/wg.conf.j2
- Allow to specifiy additional Wireguard interface options: `fwmark`, `mtu`, `table`, `preup` and `predown`
- Add host comments in Wireguard config file
> Add interface options

- tasks/setup-debian.yml
I encountered an error when running the WireGuard role (as first role) on a Debian machine. Since I think this is part of the pre-conditions of this module, I think this should be added here.
> Install GPG to be able to import WireGuard key

- CHANGELOG.md
- meta/main.yml
- tasks/setup-fedora.yml
This seems to be enough to enable wireguard on my fedora machine.
> Add basic fedora support

- README.md
- templates/wg.conf.j2
Often, more than one iptables command is required for a meaningful firewall setup. Of course we can just append all commands with '&&' but that isn't readable depending on the amount of commands.
With this pull request, multiple  postup/postdown/preup/predown commands are created if specified
> Ability to create multiple postup/postdown/preup/predown commands

- CHANGELOG.md
- README.md
- handlers/main.yml
- tasks/main.yml
Newer versions of WireGuard (around November 2019) introduced `wg syncconf` subcommand. This has the advantage that changes to the WireGuard configuration can be applied without disturbing existing connections. With this change this role tries to use `wg syncconf` subcommand when available. This even works if you have hosts with older and newer WireGuard versions.
> Use "wg syncconf" if available

- CHANGELOG.md
- handlers/main.yml
add shell options to syncconf handler to fail fast in case of error
> Shell best practice

- tasks/setup-debian.yml
I was getting the following error _on the second run_ when attempting to use this role to provision a Wireguard server on Debian 9.12.
```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
gpg : Depends: gpgconf (= 2.2.19-3) but it is not going to be installed
Depends: libassuan0 (>= 2.5.0) but 2.4.3-2 is to be installed
Depends: libc6 (>= 2.25) but 2.24-1
1+deb9u4 is to be installed
Depends: libgcrypt20 (>= 1.8.0) but …
```
> Bugfix: Install gnupg instead of gpg for Debian

- CHANGELOG.md
- files/debian/etc/apt/preferences.d/limit-unstable
- tasks/setup-debian.yml
I found out that my changes to add debian support no longer worked.
* Wireguard key was missing from keyserver and no longer needed to be added for buster-backports.
* `buster-backports` contains wireguard, using this for <= buster
* no longer pin packages from `unstable`. No need to pin backports, it has a lower priority than main repo.
> Use wireguard from buster-backports on debian if needed

- tasks/main.yml
- tasks/setup-archlinux.yml
- vars/packages-archlinux.yml
- vars/packages.yml
Arch Linux ships a Linux kernel > 5.6 and doesn't require DKMS.
Move the package list variable to (distribution-specific) var files.
For the Arch Linux LTS kernel (5.4) a binary wireguard-lts package is
provided in [core].
> Use Arch Linux specific package list

- CHANGELOG.md
- README.md
- defaults/main.yml
- meta/main.yml
- tasks/main.yml
- tasks/setup-archlinux.yml
- tasks/setup-centos.yml
- tasks/setup-debian.yml
- tasks/setup-fedora.yml
- tasks/setup-ubuntu.yml
- vars/packages-archlinux.yml
- vars/packages.yml
- Support Ubuntu 20.04
- Add Debian Buster to Galaxy metadata
- Handle kernel's that already include "wireguard" module (that's mainly Archlinux and Ubuntu 20.04 at the moment)
> Support Ubuntu 20.04

- tasks/setup-debian-vanilla.yml
- tasks/setup-debian.yml
On openstack Debian images, the kernel is different, so we need to install different kernel headers, too.
> Fix on debian openstack images

- CHANGELOG.md
- README.md
- templates/wg.conf.j2
In order to support peers that are not managed in Ansible, add support to add peers not managed by ansible to WireGuard config. This allows easily defining peers without endpoint that can talk to all nodes being deployed. Especially useful for workstations without an endpoint address.
Add variable wireguard_unmanaged_peers that appends the peers into config.
This closes #41, and closes #45.
Example of how to use this:
```yaml
vpn:
hosts:
server1:
...
server2:
...
wireguard_unmanaged_peers:
client.example.com:
public_key: 5zsSBeZZ8P9pQaaJvY9RbELQulcwC5VBXaZ93egzOlI=
allowed_ips: 10.0.0.3/32
vars:
wireguard_unmanaged_peers:
client.example.com:
public_key: 5zsSBeZZ8P9pQaaJvY9RbELQulcwC5VBXaZ93egzOlI=
allowed_ips: 10.0.0.3/32
```
> Add support for unmanaged WireGuard peers

- handlers/main.yml
https://github.com/githubixx/ansible-role-wireguard/blob/ee456757edfe77fc5004567b0e70ee88bcde612c/handlers/main.yml#L17
systemctl is-active wg-quick@wg-quick@{{ wireguard_interface|quote }} || systemctl start wg-quick@{{ wireguard_interface|quote }}
I was just reading through this and saw what looks like an editing bug.
Anyway, the whole check `systemctl is-active wg-quick@wg-quick@{{ wireguard_interface|quote }} ||` because `systemctl start` already returns 0 for a system already started.
> fix typo in syncconf handler

- CHANGELOG.md
- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- tasks/setup-macosx.yml
I added basic support for `macOS`
- Add the `ansible_os_is_linux` internal variable to discern between a Linux system and a macOS one
- Conditional choice for `wireguard_remote_directory` default value. It defaults to `/etc/wireguard` on Linux and `/opt/local/etc/wireguard` (i.e. Macports default path) on macOS
- Add configurable `owner` and `group` for the configuration file `wg0.conf`. The group defaults on `wheel` on `macOS`
- No handlers for macOS 
- No kernel module activation on macOS
- Add instructions into the `README.md` on how to run the VPN on macOS manually
> Add basic macOS support

- CHANGELOG.md
- tasks/setup-ubuntu.yml
`ppa:wireguard/wireguard` is gone. So it can't no longer be used for Ubuntu 18.04. Instead `wireguard` metapackage can be used now which is available in universe repository.
> Fix Ubuntu 18 install

- CHANGELOG.md
- defaults/main.yml
- tasks/main.yml
- tasks/setup-debian-vanilla.yml
- templates/etc/wireguard/wg.conf.j2
Closes #65.
Setting the private key of the WireGuard VPN server allows to keep all the client configurations.
I didn't put the variable in `README.md` because it may be not recommended for everyone, and requires to encrypt the key in some way, but now it is possible to set it.
When testing my changes, I noticed the check mode was broken. It is now fixed in a commit.
I also changed a shell task to command, the later being recommended over shell.
> Add wireguard_private_key variable

- CHANGELOG.md
- tasks/setup-debian-raspbian.yml
Use Debian backports instead of unstable to get wireguard. This is a more stable solution and has less impact on the system.
Unfortunately a reboot is still required.
> Raspberry Pi: Use Backports instead of Debian Unstable

- tasks/setup-fedora-32.yml
- tasks/setup-fedora.yml
This commit fixes Fedora >= 33 support.
Fedora 32 still installs the copr repo and the dkms module through 
setup-fedora-32.yml I assume that is still necessary for Fedora 32, 
though I have no box to test it with.
If the user is on Fedora 33 or higher, the default setup-fedora.yml is
used, which no longer installs the copr repo, nor the dkms module since
neither are necessary anymore: the wireguard module has been merged
in the upstream kernel and wireguard-tools is in the base OS.
> Fix Fedora >= 33 support

- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
On my desktop machine, I manually start/stop the wireguard service using wg-quick. This change allows disabling the service to allow wg-quick to do its thing.
> Allow disabling service

- tasks/main.yml
- tasks/setup-archlinux.yml
- tasks/setup-centos-7.yml
- tasks/setup-centos-8.yml
- tasks/setup-debian-pve-variant.yml
- tasks/setup-debian-raspbian.yml
- tasks/setup-debian-vanilla.yml
- tasks/setup-debian.yml
- tasks/setup-fedora-32.yml
- tasks/setup-fedora.yml
- tasks/setup-macosx.yml
- tasks/setup-opensuse leap.yml
- tasks/setup-ubuntu.yml
This PR fixes #109 & #81 
Background to the change on the tag:
Tags are evaluated at the start of a play, so any include, that is evaluated at runtime, will not result in having any tag-functionality applied to included tasks/roles, unless tags are applied via the parameter "apply".
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#tag-inheritance-for-includes-blocks-and-the-apply-keyword
By adding "tags" to the main.yml-include_tasks-Task, this task is respected, if "wg-install" is given via "skip-tags" or "tags".
By adding "apply"-"tags", the defined tag "wg-install" ist applied to all included tasks and all included tasks are handled, when given the tag "wg-install" via "tags"-option.
As for no_log:
Default verbosity of 0 or slight increases up to 2 will now not …
> Fix tag "wg-install" & Add no_log

- CHANGELOG.md
- handlers/main.yml
- meta/main.yml
- molecule/kvm/converge.yml
- tasks/main.yml
- tasks/setup-almalinux-8.yml
- tasks/setup-archlinux.yml
- tasks/setup-centos-7.yml
- tasks/setup-centos-8.yml
- tasks/setup-debian-pve-guest-variant.yml
- tasks/setup-debian-pve-host-variant.yml
- tasks/setup-debian-raspbian.yml
- tasks/setup-debian-vanilla.yml
- tasks/setup-debian.yml
- tasks/setup-fedora.yml
- tasks/setup-macosx.yml
- tasks/setup-opensuse leap.yml
- tasks/setup-rocky-8.yml
- tasks/setup-ubuntu.yml
- templates/etc/wireguard/wg.conf.j2
* The resulting order of WireGuard's hooks should coincide with its lifecycle
* Using FQCNs is recommended by the official Ansible documentation
> General improvements

- CHANGELOG.md
- templates/etc/wireguard/wg.conf.j2
ATM the template rendering the WireGuard configuration only checks if `wireguard_save_config` is set and if so sets `SaveConfig = true`. So setting `wireguard_save_config: "false"` had no effect. This PR fixes this behavior.
Fixes https://github.com/githubixx/ansible-role-wireguard/issues/136
> honor wireguard_save_config value

- defaults/main.yml
- molecule/kvm/molecule.yml
- molecule/kvm/prepare.yml
- tasks/setup-rocky-8.yml
Hello, I've been toying with RockyLinux on Raspberry 3 (`aarch64`) and needed the [non-standard kernel](https://www.wireguard.com/install/) installation, as documented by wireguard.
Although my use case is very specific, it should work with any custom kernel on `aarch64`, `ppc64le` and `x86_64`.  
It might also work on AlmaLinux (not tested)
I expanded on the logic you had for CentOS7 setup with a new variable : wireguard_rockylinux8_installation_method, defaulting to the classic EPEL/Elrepo installation process.
> Add non-standard kernel installation for RockyLinux 8

- tasks/setup-debian-vanilla.yml
Same as in https://github.com/DataDog/ansible-datadog/pull/377
> fix: Do not require lsb-release on Debian

- CHANGELOG.md
- README.md
- meta/main.yml
- molecule/kvm/molecule.yml
- tasks/setup-almalinux.yml
- tasks/setup-archlinux.yml
- tasks/setup-rocky.yml
- add support for Rocky Linux 9 (original PR from @vincentDcmps: https://github.com/githubixx/ansible-role-wireguard/pull/163)
- add support for AlamaLinux 9 (original PR from @trunet: https://github.com/githubixx/ansible-role-wireguard/pull/164)
- add `EL9` to `meta/main.yml`
- require Ansible >= `2.11` as Rocky Linux is only supported with this version or above
- `ansible-lint`: use `community.general.pacman` module instead of `ansible.builtin.pacman` for Archlinux setup
> Rocky Linux + AlmaLinux support

- CHANGELOG.md
- README.md
- templates/etc/wireguard/wg.conf.j2
First of all, thanks for the great work, this role was really useful for one of my project.
Until now, it has been impossible for a host to have multiple IPs inside the VPN. This prevents a lot of use-cases, especially dual-stack network (one IPv4 and one IPv6). Furthermore, putting an IPv6 inside the `wireguard_address` produced an invalid configuration file, since the IP got suffixed by the `/32` mask : 
https://github.com/githubixx/ansible-role-wireguard/blob/f6a6e4680a6061622bee2351daadaa30f60f953d/templates/etc/wireguard/wg.conf.j2#L56
This PR aims to fix IPv6 support and allow using multiple IPs.
To do this, the PR implements the `wireguard_addresses` variable. This variable can contain an array of IPv4 or IPv6 addresses to be used inside the Wireguard network. The old way of …
> Allow to use multiple addresses and added IPv6 support

- CHANGELOG.md
- README.md
- defaults/main.yml
- tasks/setup-centos-7.yml
It needs to be rebooted to make the WireGuard kernel module available.
> Add reboot to the standard mode

- CHANGELOG.md
- README.md
- defaults/main.yml
- tasks/setup-almalinux-8.yml
- tasks/setup-centos-7.yml
- tasks/setup-debian-pve-guest-variant.yml
- tasks/setup-debian-pve-host-variant.yml
- tasks/setup-debian-raspbian-buster.yml
- tasks/setup-debian-vanilla.yml
- tasks/setup-rocky-8.yml
previously disable the cache update was only possible on ubuntu using the generic name wireguard_update_cache it can be enabled for all operating systems
> option wireguard_update_cache to disable refresh

- tasks/main.yml
Currently it would fail with "'wireguard__restart_interface' is undefined"
> Make it possible to use wg-config tag only

- templates/etc/wireguard/wg.conf.j2
Adds the `Name = ` prefix in host name comment line of wireguard config to allow this [wg-info](https://github.com/asdil12/wg-info) neat little script to display host name.
> Prefix host name comment with 'Name =' for wg-info

- CHANGELOG.md
- README.md
- defaults/main.yml
- tasks/main.yml
Setting up tunnels can be error prone and it's nice to have the ability to review a past deployed working configuration when one accidently breaks a tunnel.
By simply leveraging the `backup` directive of the `template` ansible module, one easily let the role user control if that mechanism is useful to them.
Best regards
> Wireguard conf backup

- README.md
- defaults/main.yml
- tasks/main.yml
This PR enables skipping the wg kernel module install based on tag (`wg-install-kernel-module`) or role variable `wireguard_install_kernel_module`.
Fixes #190
> Enable skipping of wg kernel module install

- templates/etc/wireguard/wg.conf.j2
> Hide peers with empty endpoints
